name: Fetch Team Members on PR Submission


on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Allows manual trigger
  pull_request:
    branches:
      - develop  # Trigger for PRs targeting the 'develop' branch
    types: [opened]  # Trigger only when the PR is opened
    

permissions:
  contents: read
  pull-requests: read

jobs:
  fetch_team_members:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Define and use Team Names in one step
      run: |
        Team_Members=("teamahdfc" "teambsidgs")
        Team_A="${Team_Members[0]}"
        Team_B="${Team_Members[1]}"
        echo "Team A: $Team_A"
        echo "Team B: $Team_B"
        echo "TEAM_A=$Team_A" >> $GITHUB_ENV
        echo "TEAM_B=$Team_B" >> $GITHUB_ENV

    - name: Fetch Team A Members
      run: |
        echo "Fetching Team A Members"
        TEAM_A="teamahdfc"  # Make sure this is set to the correct Team ID

        # Install jq for JSON parsing
        sudo apt-get update && sudo apt-get install -y jq
        
        # API call to get team members
        TEAM_A_MEMBERS=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/orgs/hdfcorg/teams/$TEAM_A/members")
        
         # Debugging: Print the raw response
        echo "Raw API Response:"
        echo "$TEAM_A_MEMBERS"
    
        # Ensure the response is a valid JSON array before using jq
        if echo "$TEAM_B_MEMBERS" | jq empty 2>/dev/null; then
          echo "Parsed Team B Members:"
          echo "$TEAM_A_MEMBERS" | jq '.[] | {id, login, url}'
        else
          echo "Error: API did not return a valid JSON array"
          exit 1
        fi
    - name: Fetch Team B Members
      run: |
        echo "Fetching Team B Members"
        TEAM_B="teambsidgs"  # Make sure this is set to the correct Team ID

        # API call to get team members
        TEAM_B_MEMBERS=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/orgs/hdfcorg/teams/$TEAM_B/members")
        
         # Debugging: Print the raw response
        echo "Raw API Response:"
        echo "$TEAM_B_MEMBERS"
    
        # Ensure the response is a valid JSON array before using jq
        if echo "$TEAM_B_MEMBERS" | jq empty 2>/dev/null; then
          echo "Parsed Team B Members:"
          echo "$TEAM_B_MEMBERS" | jq '.[] | {id, login, url}'
        else
          echo "Error: API did not return a valid JSON array"
          exit 1
        fi   
